/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SuperShop;

import javax.swing.JOptionPane;

/**
 *
 * @author Ali
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        BtmLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tala = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setBackground(new java.awt.Color(255, 204, 204));
        userField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 310, 50));

        passwordField.setBackground(new java.awt.Color(255, 204, 204));
        passwordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 310, 50));

        BtmLogin.setBackground(new java.awt.Color(255, 255, 255));
        BtmLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtmLogin.setText("Login");
        BtmLogin.setBorder(null);
        BtmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmLoginActionPerformed(evt);
            }
        });
        BtmLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtmLoginKeyPressed(evt);
            }
        });
        getContentPane().add(BtmLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 90, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lock.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/man.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Forgot Psaaword");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 220, 20));

        tala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tala-removebg-preview.png"))); // NOI18N
        getContentPane().add(tala, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 240, 170));

        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login eye-3.gif"))); // NOI18N
        getContentPane().add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void BtmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmLoginActionPerformed
      String username = "admin";
      String password = "123";
     
      String user = userField.getText();
      String pass = passwordField.getText();
      
      if(password.equals(pass)){
          setVisible(false);
          dispose();
          new UserManagement().setVisible(true); 
          
      }else{
          JOptionPane.showMessageDialog(rootPane, "Invalid Password !");
      }
    }//GEN-LAST:event_BtmLoginActionPerformed

    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new progotPassword().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void BtmLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtmLoginKeyPressed
        
    }//GEN-LAST:event_BtmLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtmLogin;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel tala;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
